pipeline {
    
	agent any
	
	tools {
        maven "MAVEN3"
        jdk "Java8"
    }

    environment {
        cluster = "vproprod"
        service = "vpro-prod-service"
    }
	
    stages{
        stage ('Deploy to ECS staging'){
            steps {
                withAWS(credentials: 'awscreds', region: 'us-east-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }
    
    }

